name: ratemyustaad
description: "A professor rating application for students."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase packages
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  
  # State management
  provider: ^6.1.1
  
  # UI packages
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
