// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2xp_jl6cuA9-7epy98WcTN_SK7WQMZVM',
    appId: '1:128410338756:web:4a6368c61f48c6211b9091',
    messagingSenderId: '128410338756',
    projectId: 'rate-my-ustaad',
    authDomain: 'rate-my-ustaad.firebaseapp.com',
    databaseURL: 'https://rate-my-ustaad-default-rtdb.firebaseio.com',
    storageBucket: 'rate-my-ustaad.firebasestorage.app',
    measurementId: 'G-3JH6K75EPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMfrz0BPgbFVx_zI6fESlv6bGxxhlSjp8',
    appId: '1:128410338756:android:6e1ffc527687a0e61b9091',
    messagingSenderId: '128410338756',
    projectId: 'rate-my-ustaad',
    databaseURL: 'https://rate-my-ustaad-default-rtdb.firebaseio.com',
    storageBucket: 'rate-my-ustaad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_cALPjc-wgWX7NBUHqXWY0lVd4tGWXpY',
    appId: '1:128410338756:ios:ee8eccb4d62bafc91b9091',
    messagingSenderId: '128410338756',
    projectId: 'rate-my-ustaad',
    databaseURL: 'https://rate-my-ustaad-default-rtdb.firebaseio.com',
    storageBucket: 'rate-my-ustaad.firebasestorage.app',
    androidClientId:
        '128410338756-inh8ei73e6oo171q0avttrtk5hjvomjk.apps.googleusercontent.com',
    iosClientId:
        '128410338756-qfrqg4lb4ta1eh0594jamtj0vhe61p7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.ratemyustaad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_cALPjc-wgWX7NBUHqXWY0lVd4tGWXpY',
    appId: '1:128410338756:ios:ee8eccb4d62bafc91b9091',
    messagingSenderId: '128410338756',
    projectId: 'rate-my-ustaad',
    databaseURL: 'https://rate-my-ustaad-default-rtdb.firebaseio.com',
    storageBucket: 'rate-my-ustaad.firebasestorage.app',
    androidClientId:
        '128410338756-inh8ei73e6oo171q0avttrtk5hjvomjk.apps.googleusercontent.com',
    iosClientId:
        '128410338756-qfrqg4lb4ta1eh0594jamtj0vhe61p7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.ratemyustaad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2xp_jl6cuA9-7epy98WcTN_SK7WQMZVM',
    appId: '1:128410338756:web:34500c3becb8acb01b9091',
    messagingSenderId: '128410338756',
    projectId: 'rate-my-ustaad',
    authDomain: 'rate-my-ustaad.firebaseapp.com',
    databaseURL: 'https://rate-my-ustaad-default-rtdb.firebaseio.com',
    storageBucket: 'rate-my-ustaad.firebasestorage.app',
    measurementId: 'G-MPHJD7GCHX',
  );
}
