// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX5VCHRFr9ye-D-I31jCRBEwjMgABWFrc',
    appId: '1:425867193513:web:59eadb85ead6076866cdb8',
    messagingSenderId: '425867193513',
    projectId: 'ratemyustaad2',
    authDomain: 'ratemyustaad2.firebaseapp.com',
    storageBucket: 'ratemyustaad2.firebasestorage.app',
    measurementId: 'G-TJBKEM90J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_7d1Yhr-HSKOTUUPQ5P_xMRGqWoc-19g',
    appId: '1:425867193513:android:8f63b025bae903bf66cdb8',
    messagingSenderId: '425867193513',
    projectId: 'ratemyustaad2',
    storageBucket: 'ratemyustaad2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD6IQSkzfhD4lX3fYprGiNvHETu13XElQ',
    appId: '1:425867193513:ios:fb75ab6494ed88a566cdb8',
    messagingSenderId: '425867193513',
    projectId: 'ratemyustaad2',
    storageBucket: 'ratemyustaad2.firebasestorage.app',
    iosClientId: '425867193513-pe25gp5np69hpuq7ahmu8lm4gpp2a1uv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ratemyustaad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD6IQSkzfhD4lX3fYprGiNvHETu13XElQ',
    appId: '1:425867193513:ios:fb75ab6494ed88a566cdb8',
    messagingSenderId: '425867193513',
    projectId: 'ratemyustaad2',
    storageBucket: 'ratemyustaad2.firebasestorage.app',
    iosClientId: '425867193513-pe25gp5np69hpuq7ahmu8lm4gpp2a1uv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ratemyustaad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX5VCHRFr9ye-D-I31jCRBEwjMgABWFrc',
    appId: '1:425867193513:web:c656268adf59df7266cdb8',
    messagingSenderId: '425867193513',
    projectId: 'ratemyustaad2',
    authDomain: 'ratemyustaad2.firebaseapp.com',
    storageBucket: 'ratemyustaad2.firebasestorage.app',
    measurementId: 'G-QL1Q7QF2L9',
  );

}